<!DOCTYPE html>
<!-- saved from url=(0041)# -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="http://v3.bootcss.com/favicon.ico">

    <title>文件提交</title>
	
    <link href="/public/css/bootstrap.min.css" rel="stylesheet">

	<script src="/public/js/jquery.min.js"></script>
    <script src="/public/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="http://cdn.bootcss.com/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
        <p class="text-center" href="#">提交文件使用</p>

</nav>

<div class="container">
    <div class="row">
        <div class="col-lg-4"></div>
    <form role="form" class="col-lg-4" style="" id="sub_form">
        <div class="form-group"> <input type="text" class="form-control" name="sessionid" value="1498983068_28666998e57c8d621d5a_15470#uvdjbi"> </div>
        <div class="form-group"> <input type="text" class="form-control" name="os" value="ios"> </div>
        <div class="form-group"> <input type="text" class="form-control" name="version" value="2.2.2"> </div>
        <div class="form-group"> <input type="text" class="form-control" name="filmid" value="A5uZMkMJfuM"> </div>
        <div class="form-group"> <input type="text" class="form-control" name="content" value="大灰机"> </div>
        <div class="form-group"> <input type="text" class="form-control" name="rose" value="9.0"> </div>
        <div class="form-group"> <input type="file" name="pic" /> </div>
        <div class="form-group">
            <button type="button" class="btn btn-primary btn-lg btn-block" id="submit">登录</button>
        </div>
        <p>如有任何问题，请联系黑白客服：400-862-5211</p>

    </form>
        <div class="col-lg-4"></div>
    </div>
</div>
</body>
<script>
$(document).keydown(function(e){
	if(e.keyCode == 13){
		$("#submit").click();
	}
});

var flag = false;
$("#submit").on("click",function(){
	var D = new FormData($("#sub_form")[0]);
	$.ajax({
		url: "/film/comment",
		type: "POST",
		beforeSend: function(){},
		data: D,
		cache: false,
		contentType: false,
		processData: false,
	}).done(function(data){
		console.log(data);
		data = JSON.parse(data);
	}).fail(function(data){
	
	});
});
</script>
</html>
