<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>订阅查询</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- 公共css -->
    <link rel="stylesheet" href="/public/css/bootstrap.min.css">
    <link rel="stylesheet" href="/public/css/AdminLTE.min.css">
    <link rel="stylesheet" href="/public/css/base.css">

</head>
<body class="hold-transition skin-blue layout-top-nav">
<!-- wrapper begin-->
<div class="wrapper">
    <header class="main-header">
        <!-- 导航 begin-->
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                    <!-- logo begin-->
                    <div class="logo">
                        <a href="#" class="navbar-brand"><img src="http://www.newasp.net/attachment/soft/2015/0512/151436_40558391.png"></a>
                        <h4><a href="#">跨年晚会后台</a></h4>
                    </div>
                    <!-- logo end-->
                </div>

                <div class="collapse navbar-collapse nav_user" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav " id="nav_left">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">弹幕审核<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/">弹幕审核</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">预约信息查看<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/CountdownParty/subscribe/collegesSubscribes">院校预约总人数</a></li>
                                <li><a href="/CountdownParty/subscribe/subscribeUserInfo">预约用户详细信息</a></li>
                            </ul>
                        </li>
                        <li>
                            <div class="search">
                                <a href="#" class="glyphicon glyphicon-search"></a>
                            </div>
                        </li>
                    </ul>
					<!-- 搜索 begin-->
                   <div class="nav_search">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                            <input class="form-control" type="text" placeholder="搜索">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-remove"></i></span>
                        </div>
                    </div>
                    <!-- 搜索 end-->
                    <!--  退出登录 begin--> 
                    <ul class="nav navbar-nav navbar-right" id="navbar-right">
                        <li class="dropdown log_out">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">退出系统 <span class="caret"></span></a>
                            <ul class="dropdown-menu logout_menu">
                                <li><a href="#"><i class="glyphicon glyphicon-lock"></i>修改密码</a></li>
                                <li><a href="/index/logout"><i class="glyphicon glyphicon-off"></i>退出</a></li>
                            </ul>
                        </li>
                    </ul>
                    <!-- 退出登录 end-->
                </div>
            </div>
        </nav>
        <!-- 导航 end-->
    </header>
    <!-- content-wrapper begin -->
    <div class="content-wrapper">
        <!-- content-header begin-->
        <section class="content-header">
            <div class="row">
                <div class="col-xs-12 col-md-8">
                  <h3>订阅查看</h3>
                </div>
            </div>
        </section>
        <!-- content-header begin-->
        
        <!-- content begin-->
        <section class="content user_center">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box box-primary">
                        <div class="box-body no-padding">
                            <div class="table-responsive mailbox-messages">
                                <table class="table table-hover table-striped">
                                    <thead>
                                        <tr>
                                            <th>学校</th>
                                            <th>订阅人数</th>
                                        </tr>
                                    </thead>
                                    <tbody id="danmulist">
									<?php
									if(isset($items) && $items):
       									foreach( $items as $i ):
										echo "<tr><td>{$i['school']}</td><td>{$i['count']}</td></tr>";
										endforeach;
									endif;
									?>
                                    </tbody>
									<tfoot>
										<tr><td colspan='6' id='emptymsg'>订阅信息</td></tr>
									</tfoot>
                                </table>
                                <!-- /.table -->
                            </div>
                            <!-- /.mail-box-messages -->
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /. box -->
                    <!-- 分页 begin-->
                    <div class="text-center">
                        <nav aria-label="Page navigation">
                            <ul class="pagination" id="pagination">
							<?php
							if($curPage&&$curSize&&$maxNum){
								$pageAmount = intval($maxNum/$curSize);
								if ($maxNum%$curSize)
									$pageAmount++;
									if($curPage>1){
										echo '<li><a href="/CountdownParty/subscribe/collegesSubscribes?page='.($curPage-1).'&size='.($curSize).'">&laquo;</a></li>';
									}

									for($i=1; $i<=$pageAmount; $i++){
               							if($curPage==$i)
                  							echo '<li><a class="selected" href="/CountdownParty/subscribe/collegesSubscribes?page='.$i.'&size='.($curSize).'">'.$i.'</a></li>';
               							else
                  							echo '<li><a href="/CountdownParty/subscribe/collegesSubscribes?page='.$i.'&size='.($curSize).'">'.$i.'</a></li>';
           							}

           							if($curPage<$pageAmount){
              							echo '<li><a href="/CountdownParty/subscribe/collegesSubscribes?page='.($curPage+1).'&size='.($curSize).'">&raquo;</a></li>';
           							}
        					}
        					?>
                            </ul>
                        </nav>
                    </div>
                    <!-- 分页 end-->
                </div>
            </div>
        </section>
        <!-- content end-->
    </div>
    <!-- content-wrapper end -->
    <!-- main-footer begin-->
    <footer class="main-footer">
        <div class="pull-right hidden-xs"><b>Version</b> 1.0.0</div>
        <strong>Copyright © 2017 <a href="#">黑白校园</a> . All rights reserved.</strong>
    </footer>
    <!-- main-footer end-->
</div>
<!-- wrapper end-->

<script src="/public/js/jquery.min.js"></script>
<script src="/public/js/bootstrap.min.js"></script>
<script src="/public/js/app.min.js"></script>
<script src="/public/js/html5shiv.min.js"></script>
<script src="/public/js/respond.min.js"></script>
<script src="/public/js/base.js"></script>
<script>
    'use strict';
    $(function(){
        
		//选中分页变色
		$('ul li').find('.selected').css({'background-color':'#eee'});
    })
</script>
</body>
</html>
