<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>跨年晚会</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- 公共css -->
    <link rel="stylesheet" href="/public/css/bootstrap.min.css">
    <link rel="stylesheet" href="/public/css/AdminLTE.min.css">
    <link rel="stylesheet" href="/public/css/base.css">

</head>
<body class="hold-transition skin-blue layout-top-nav">
<!-- wrapper begin-->
<div class="wrapper">
    <header class="main-header">
        <!-- 导航 begin-->
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    
                    <!-- logo begin-->
                    <div class="logo">
                        <a href="#" class="navbar-brand"><img src="http://www.newasp.net/attachment/soft/2015/0512/151436_40558391.png"></a>
                        <h4><a href="#">跨年晚会后台</a></h4>
                    </div>
                    <!-- logo end-->
                </div>

                <div class="collapse navbar-collapse nav_user" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav " id="nav_left">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">弹幕审核<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/">弹幕审核</a></li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">预约信息查看<span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="/CountdownParty/subscribe/collegesSubscribes">院校预约总人数</a></li>
                                <li><a href="/CountdownParty/subscribe/subscribeUserInfo">预约用户详细信息</a></li>
                            </ul>
                        </li>
                        <li>
                            <div class="search">
                                <a href="#" class="glyphicon glyphicon-search"></a>
                            </div>
                        </li>
                    </ul>
					<!-- 搜索 begin-->
                   <div class="nav_search">
                        <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>
                            <input class="form-control" type="text" placeholder="搜索">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-remove"></i></span>
                        </div>
                    </div>
                    <!-- 搜索 end-->
                    <!--  退出登录 begin--> 
                    <ul class="nav navbar-nav navbar-right" id="navbar-right">
                        <li class="dropdown log_out">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">退出系统 <span class="caret"></span></a>
                            <ul class="dropdown-menu logout_menu">
                                <li><a href="#"><i class="glyphicon glyphicon-lock"></i>修改密码</a></li>
                                <li><a href="/index/logout"><i class="glyphicon glyphicon-off"></i>退出</a></li>
                            </ul>
                        </li>
                    </ul>
                    <!-- 退出登录 end-->
                </div>
            </div>
        </nav>
        <!-- 导航 end-->
    </header>
    <!-- content-wrapper begin -->
    <div class="content-wrapper">
        <!-- content-header begin-->
        <section class="content-header">
        </section>
        <!-- content-header begin-->
        
        <!-- content begin-->
        <section class="content user_center">
        </section>
    </div>
    <footer class="main-footer">
        <div class="pull-right hidden-xs"><b>Version</b> 1.0.0</div>
        <strong>Copyright © 2017 <a href="#">黑白校园</a> . All rights reserved.</strong>
    </footer>
</div>

<script src="/public/js/jquery.min.js"></script>
<script src="/public/js/bootstrap.min.js"></script>
<script src="/public/js/app.min.js"></script>
<script src="/public/js/html5shiv.min.js"></script>
<script src="/public/js/respond.min.js"></script>
<script src="/public/js/base.js"></script>
</body>
</html>
