    <!-- content-wrapper begin -->
    <div class="content-wrapper">
        <!-- content-header begin-->
        <section class="content-header">
            <div class="row">
                <div class="col-xs-12 col-md-8">
                  <h3>用户列表</h3>
                </div>
            </div>
        </section>
        <!-- content-header begin-->
        
        <!-- content begin-->
        <section class="content user_center">
            <div class="row">
                <div class="col-xs-12">
                    <div class="box box-primary">
                        <div class="box-body no-padding">
                            <div class="table-responsive mailbox-messages">
                                <table class="table table-hover table-striped">
                                    <thead>
                                        <tr>
                                            <th>ID</th>
                                            <th>头像</th>
                                            <th>微信昵称</th>
                                            <th>注册时间</th>
                                            <th>性别</th>
                                            <th>地区</th>
                                        </tr>
                                    </thead>
                                    <tbody id="danmulist">
                                    </tbody>
									<tfoot>
										<tr><td colspan='6' id='emptymsg'></td></tr>
									</tfoot>
                                </table>
                                <!-- /.table -->
                            </div>
                            <!-- /.mail-box-messages -->
                        </div>
                        <!-- /.box-body -->
                    </div>
                    <!-- /. box -->
                </div>
            </div>
        </section>
        <!-- content end-->
    </div>
