<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>登录</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- 公共css -->
    <link rel="stylesheet" href="/public/css/bootstrap.min.css">
    <link rel="stylesheet" href="/public/css/AdminLTE.min.css">
    <link rel="stylesheet" href="/public/css/base.css">

    <!-- 本页面用到的css -->
    <link rel="stylesheet" href="/public/css/login.css">

</head>
<body>
<!-- wrapper begin-->
<div class="wrapper login">
    <!-- content-wrapper begin-->
    <div class="content-wrapper">
        <!-- content begin-->
        <section class="content">
            <!-- row begin-->
            <div class="row">
                <!-- col-md-6 begin-->
                <div class="col-lg-6">
                    <!-- box begin-->
                    <div class="box box-info">
                        <!-- box-header begin-->
                        <div class="box-header with-border">
                            <h3 class="box-title">小程序管理后台</h3>
                        </div>
                        <!-- box-header end-->
                        <!-- form begin-->
                        <form class="form-horizontal" method="post" action="/index/login">
                            <div class="box-body">
                                <div class="form-group">
                                    <label for="inputEmail3" class="col-sm-3 control-label">用户名</label>
                                    <div class="col-sm-9">
                                        <input  class="form-control" name='username'  placeholder="请输入您的用户名">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="inputPassword3" class="col-sm-3 control-label">密码</label>
                                    <div class="col-sm-9">
                                        <input type="password" name='password' class="form-control"  placeholder="请输入您的登录密码">
                                    </div>
                                  <!-- <span class="error_prompt">密码格式错误</span> -->
                                </div>
                                <div class="form-group">
                                    <div class="col-sm-offset-3 col-sm-9">
										<?php if (!empty($errmsg)) :?>
                                         <label style="color:red">用户名或者密码错误</label>
										<?php endif;?>
                                    </div>
                                </div>
                            </div>
                          
                            <div class="box-footer text-center">
                                <button type='submit' class="btn btn-primary">登录</button>
                            </div>
                        </form>
                        <!-- form end-->
                    </div>
                    <!-- box end-->
                </div>
                <!-- col-md-6 end-->
            </div>
           <!-- row end-->
        </section>
        <!-- content end-->
    </div>
    <!-- content-wrapper begin-->
    <!-- main-footer begin-->
    <footer class="main-footer">
        <div class="pull-right hidden-xs"><b>Version</b> 1.0.0</div>
        <strong>Copyright © 2019 <a href="#"></a> . All rights reserved.</strong>
    </footer>
    <!-- main-footer end-->
</div>  
<!-- wrapper end-->

<!-- 公共js -->
<script src="/public/js/jquery.min.js"></script>
<script src="/public/js/bootstrap.min.js"></script>
<script src="/public/js/app.min.js"></script>
<script src="/public/js/html5shiv.min.js"></script>
<script src="/public/js/respond.min.js"></script>


</body>
</html>
